//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowMage.OverlayPlugin.Updater {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RainbowMage.OverlayPlugin.Updater.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check for {0} through ACT failed, retrying with GitHub API..
        /// </summary>
        public static string ActUpdateCheckFailed {
            get {
                return ResourceManager.GetString("ActUpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT Update check for {0} failed, falling back to GitHub API: {1}.
        /// </summary>
        public static string ActUpdateException {
            get {
                return ResourceManager.GetString("ActUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create or empty the temporary directory &quot;{0}&quot;: {1}.
        /// </summary>
        public static string CreatingTempDirFailed {
            get {
                return ResourceManager.GetString("CreatingTempDirFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed! The download has no file size (Content-Length header is missing)..
        /// </summary>
        public static string DownloadFailedContentLengthMissing {
            get {
                return ResourceManager.GetString("DownloadFailedContentLengthMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: {0}.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring auto-update due to OverlayPlugin being a .git repo..
        /// </summary>
        public static string IgnoreUpdateDueToDotGitDirectoryMessage {
            get {
                return ResourceManager.GetString("IgnoreUpdateDueToDotGitDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch installer: {0}.
        /// </summary>
        public static string LaunchingInstallerFailed {
            get {
                return ResourceManager.GetString("LaunchingInstallerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] libcurl {
            get {
                object obj = ResourceManager.GetObject("libcurl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] libcurl_x64 {
            get {
                object obj = ResourceManager.GetObject("libcurl_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted by user..
        /// </summary>
        public static string LogAbortedByUser {
            get {
                return ResourceManager.GetString("LogAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up old files....
        /// </summary>
        public static string LogBackingUpOldFiles {
            get {
                return ResourceManager.GetString("LogBackingUpOldFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up....
        /// </summary>
        public static string LogCleaningUp {
            get {
                return ResourceManager.GetString("LogCleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting temporary files....
        /// </summary>
        public static string LogDeletingTempFiles {
            get {
                return ResourceManager.GetString("LogDeletingTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string LogDone {
            get {
                return ResourceManager.GetString("LogDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed: {0}.
        /// </summary>
        public static string LogDownloadFailed {
            get {
                return ResourceManager.GetString("LogDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading &quot;{0}&quot; into {1}....
        /// </summary>
        public static string LogDownloading {
            get {
                return ResourceManager.GetString("LogDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download was interrupted: {0}.
        /// </summary>
        public static string LogDownloadInterrupted {
            get {
                return ResourceManager.GetString("LogDownloadInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting files....
        /// </summary>
        public static string LogExtractingFiles {
            get {
                return ResourceManager.GetString("LogExtractingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction aborted by user..
        /// </summary>
        public static string LogExtractionAbortedByUser {
            get {
                return ResourceManager.GetString("LogExtractionAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to replace old directory: {0}.
        /// </summary>
        public static string LogFailedReplaceDirectory {
            get {
                return ResourceManager.GetString("LogFailedReplaceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0}: {1}.
        /// </summary>
        public static string LogFailedToDelete {
            get {
                return ResourceManager.GetString("LogFailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The installer did not finish correctly..
        /// </summary>
        public static string LogInstallerFailed {
            get {
                return ResourceManager.GetString("LogInstallerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for installer to exit....
        /// </summary>
        public static string LogInstallerWaiting {
            get {
                return ResourceManager.GetString("LogInstallerWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching installer....
        /// </summary>
        public static string LogLaunchingInstaller {
            get {
                return ResourceManager.GetString("LogLaunchingInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving directory....
        /// </summary>
        public static string LogMovingDirectory {
            get {
                return ResourceManager.GetString("LogMovingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening archive....
        /// </summary>
        public static string LogOpeningArchive {
            get {
                return ResourceManager.GetString("LogOpeningArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No retries left, update failed..
        /// </summary>
        public static string LogOverwriteFailed {
            get {
                return ResourceManager.GetString("LogOverwriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to overwrite {0}, retrying...
        ///{1}.
        /// </summary>
        public static string LogOverwriteRetry {
            get {
                return ResourceManager.GetString("LogOverwriteRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwriting old files....
        /// </summary>
        public static string LogOverwritingOldFiles {
            get {
                return ResourceManager.GetString("LogOverwritingOldFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to overwrite old files: {0}
        ///WARNING: The plugin might be in an unusable state!!
        ///Run the update check again or reinstall the plugin, otherwise it might not survive the next ACT restart..
        /// </summary>
        public static string LogOverwritingOldFilesFailed {
            get {
                return ResourceManager.GetString("LogOverwritingOldFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing old backup directory....
        /// </summary>
        public static string LogRemovingOldBackup {
            get {
                return ResourceManager.GetString("LogRemovingOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring backup....
        /// </summary>
        public static string LogRestoringBackup {
            get {
                return ResourceManager.GetString("LogRestoringBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming download....
        /// </summary>
        public static string LogResumingDownload {
            get {
                return ResourceManager.GetString("LogResumingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying again....
        /// </summary>
        public static string LogRetry {
            get {
                return ResourceManager.GetString("LogRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying in 1 second..
        /// </summary>
        public static string LogRetryAfter1s {
            get {
                return ResourceManager.GetString("LogRetryAfter1s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MSVCRT installation failed..
        /// </summary>
        public static string MsvcrtFailed {
            get {
                return ResourceManager.GetString("MsvcrtFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re missing the MS Visual C++ Redistributable for Visual Studio 2019.
        ///You&apos;ll need that for OverlayPlugin. Install it now?.
        /// </summary>
        public static string MsvcrtMissing {
            get {
                return ResourceManager.GetString("MsvcrtMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of retries..
        /// </summary>
        public static string OutOfRetries {
            get {
                return ResourceManager.GetString("OutOfRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverlayPlugin.
        /// </summary>
        public static string OverlayPluginTitle {
            get {
                return ResourceManager.GetString("OverlayPluginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently loaded version of SharpCompress is outdated!
        ///Make sure you load OverlayPlugin before any other plugins that also use SharpCompress (like ACTWebSocket)..
        /// </summary>
        public static string SharpCompressOutdatedError {
            get {
                return ResourceManager.GetString("SharpCompressOutdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled!.
        /// </summary>
        public static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string StatusCancelling {
            get {
                return ResourceManager.GetString("StatusCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}]: Done..
        /// </summary>
        public static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}]: Downloading....
        /// </summary>
        public static string StatusDownloadStarted {
            get {
                return ResourceManager.GetString("StatusDownloadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}]: Launching installer....
        /// </summary>
        public static string StatusLaunchingInstaller {
            get {
                return ResourceManager.GetString("StatusLaunchingInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}]: Preparing extraction....
        /// </summary>
        public static string StatusPreparingExtraction {
            get {
                return ResourceManager.GetString("StatusPreparingExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already on the latest version..
        /// </summary>
        public static string UpdateAlreadyLatest {
            get {
                return ResourceManager.GetString("UpdateAlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download CEF! Check the OverlayPlugin.dll tab for details..
        /// </summary>
        public static string UpdateCefDlFailed {
            get {
                return ResourceManager.GetString("UpdateCefDlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates:
        ///{0}.
        /// </summary>
        public static string UpdateCheckException {
            get {
                return ResourceManager.GetString("UpdateCheckException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Update Check.
        /// </summary>
        public static string UpdateCheckTitle {
            get {
                return ResourceManager.GetString("UpdateCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the plugin. It might not load the next time you start ACT. Retry?.
        /// </summary>
        public static string UpdateFailedError {
            get {
                return ResourceManager.GetString("UpdateFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse version:
        ///{0}.
        /// </summary>
        public static string UpdateParseVersionError {
            get {
                return ResourceManager.GetString("UpdateParseVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was updated successfully..
        /// </summary>
        public static string UpdateSliderDetails {
            get {
                return ResourceManager.GetString("UpdateSliderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was successful. Please restart ACT to load the new plugin version..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Update.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
    }
}
