//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowMage.OverlayPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RainbowMage.OverlayPlugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTWS compatibility shim enabled..
        /// </summary>
        internal static string ActwsShimEnabled {
            get {
                return ResourceManager.GetString("ActwsShimEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate handler for name {0}!.
        /// </summary>
        internal static string DuplicateHandlerError {
            get {
                return ResourceManager.GetString("DuplicateHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to dispatch event {0} to {1}! {2}.
        /// </summary>
        internal static string EventHandlerException {
            get {
                return ResourceManager.GetString("EventHandlerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the FFXIV DataRepository: {0}.
        /// </summary>
        internal static string FFXIVDataRepositoryException {
            get {
                return ResourceManager.GetString("FFXIVDataRepositoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the FFXIV DataSubscription: {0}.
        /// </summary>
        internal static string FFXIVDataSubscriptionException {
            get {
                return ResourceManager.GetString("FFXIVDataSubscriptionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected incompatible addon {0}. Please update as soon as possible!!.
        /// </summary>
        internal static string IncompatibleAddon {
            get {
                return ResourceManager.GetString("IncompatibleAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializeOverlay: Local file {0} does not exist!.
        /// </summary>
        internal static string InitOverlayLocalFileIsMissing {
            get {
                return ResourceManager.GetString("InitOverlayLocalFileIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializeOverlay: URI parse error! Please reconfigure the URL. (Config.Url = {0}): {1}.
        /// </summary>
        internal static string InitOverlayUrlError {
            get {
                return ResourceManager.GetString("InitOverlayUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JS Handler call failed: {0}.
        /// </summary>
        internal static string JsHandlerCallException {
            get {
                return ResourceManager.GetString("JsHandlerCallException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sort list by {0}: {1}.
        /// </summary>
        internal static string ListSortFailed {
            get {
                return ResourceManager.GetString("ListSortFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to dispatch unregistered event type &quot;{0}&quot;!.
        /// </summary>
        internal static string MissingEventDispatchError {
            get {
                return ResourceManager.GetString("MissingEventDispatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got a subscription for missing event &quot;{0}&quot;!.
        /// </summary>
        internal static string MissingEventSubError {
            get {
                return ResourceManager.GetString("MissingEventSubError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to call missing handler &quot;{0}&quot;!.
        /// </summary>
        internal static string MissingHandlerError {
            get {
                return ResourceManager.GetString("MissingHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to setup network parser: {0}.
        /// </summary>
        internal static string NetworkParserInitException {
            get {
                return ResourceManager.GetString("NetworkParserInitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received invalid handler call: {0}.
        /// </summary>
        internal static string OverlayApiInvalidHandlerCall {
            get {
                return ResourceManager.GetString("OverlayApiInvalidHandlerCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing events field in subscribe call: {0}!.
        /// </summary>
        internal static string OverlayApiMissingEventsField {
            get {
                return ResourceManager.GetString("OverlayApiMissingEventsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing events field in unsubscribe call: {0}!.
        /// </summary>
        internal static string OverlayApiMissingEventsFieldUnsub {
            get {
                return ResourceManager.GetString("OverlayApiMissingEventsFieldUnsub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Subscribed to {1}.
        /// </summary>
        internal static string OverlayApiSubscribed {
            get {
                return ResourceManager.GetString("OverlayApiSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register hotkey: {0}!.
        /// </summary>
        internal static string OverlayBaseRegisterHotkeyError {
            get {
                return ResourceManager.GetString("OverlayBaseRegisterHotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register hotkey {0}, {1} in EnableHotKeys()..
        /// </summary>
        internal static string RegisterHotkeyError {
            get {
                return ResourceManager.GetString("RegisterHotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unregister hotkey {0} in DisableHotKeys()..
        /// </summary>
        internal static string UnregisterHotkeyError {
            get {
                return ResourceManager.GetString("UnregisterHotkeyError", resourceCulture);
            }
        }
    }
}
